spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 920725
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lanyage.springsecurity.domain




